name: clima
description: A new Flutter application.

version: 1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  shared_preferences: ^0.5.12+4
  connectivity: ^2.0.1
  auto_size_text: ^2.1.0
  http: ^0.12.0+2
  flutter_spinkit: ^4.1.2+1
  lint: ^1.4.0-dev.d210.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900