name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  connectivity: ^2.0.1
  auto_size_text: ^2.1.0
  geolocator: ^6.1.8+1
  http: ^0.12.0+2
  flutter_spinkit: ^3.1.0
  lint: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900