name: clima_ui
description: A new Flutter application.

version: 1.2+5

publish_to: none

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: 2.1.0
  charts_flutter: 0.10.0
  flutter_swiper: 1.1.6

  clima_core:
    path: ../clima_core
  clima_domain:
    path: ../clima_domain
  clima_data:
    path: ../clima_data

  connectivity: 3.0.3
  dartz: 0.10.0-nullsafety.1
  equatable: 2.0.0
  flutter_hooks: 0.16.0
  flutter_riverpod: 0.14.0+3
  flutter_spinkit: 5.0.0
  weather_icons: 2.0.2
  hooks_riverpod: 0.14.0+3
  http: 0.13.2
  material_floating_search_bar: 0.3.4
  package_info: 2.0.0
  riverpod: 0.14.0+3
  shared_preferences: 2.0.5
  font_awesome_flutter: 9.0.0
  device_preview: 0.7.3
  url_launcher: 6.0.6
  sizer: 2.0.13

dev_dependencies:
  lint: 1.5.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true




  fonts:
  - family: Spartan MB
    fonts:
      - asset: fonts/SpartanMB-Black.otf
        weight: 900   
