name: clima_ui
description: A new Flutter application.

version: 1.1+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: 1.2.5
  shared_preferences: ^0.5.12+4
  connectivity: ^2.0.1
  auto_size_text: ^2.1.0
  http: ^0.12.0+2
  flutter_spinkit: ^4.1.2+1
  riverpod: ^0.12.1
  flutter_riverpod: 0.12.2
  flutter_hooks: 0.15.0
  hooks_riverpod: 0.12.2
  dartz: 0.9.2
  flutter_weather_icons: ^1.0.2
  material_floating_search_bar: ^0.2.6

  clima_core:
    path: ../clima_core
  clima_domain:
    path: ../clima_domain
  clima_data:
    path: ../clima_data

dev_dependencies:
  lint: ^1.4.0-dev.d210.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



  fonts:
  - family: Spartan MB
    fonts:
      - asset: fonts/SpartanMB-Black.otf
        weight: 900   
