name: clima_ui
description: A new Flutter application.

version: 1.2+5

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  clima_core:
    path: ../clima_core
  clima_domain:
    path: ../clima_domain
  clima_data:
    path: ../clima_data

  auto_size_text: 3.0.0-nullsafety.0
  equatable: 2.0.3
  flutter_hooks: 0.17.0
  flutter_riverpod: 0.14.0+3
  flutter_spinkit: 5.1.0
  weather_icons: 3.0.0
  hooks_riverpod: 0.14.0+4
  material_floating_search_bar:
    git:
      url: https://github.com/CentaurusApps/material_floating_search_bar.git
      ref: allow-passing-system-overlay-style
  package_info: 2.0.2
  riverpod: 0.14.0+3
  shared_preferences: 2.0.7
  font_awesome_flutter: 9.1.0
  device_preview: 0.7.4
  url_launcher: 6.0.10
  sizer: 2.0.13

dev_dependencies:
  lint: 1.7.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
