name: clima_data
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clima_core:
    path: ../clima_core
  clima_domain:
    path: ../clima_domain

  connectivity: 3.0.6

  flutter:
    sdk: flutter

  http: 0.13.3
  riverpod: 0.14.0+3
  shared_preferences: 2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: 1.6.0
  test: 1.16.8
