name: clima_data
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dartz: 0.9.2
  http: 0.12.2
  connectivity: 2.0.2
  riverpod: 0.12.4
  shared_preferences: ^0.5.12+4

  clima_core:
    path: ../clima_core
  clima_domain:
    path: ../clima_domain

dev_dependencies:
  lint: ^1.4.0-dev.d210.1
  test: ^1.16.0-nullsafety.5
  flutter_test:
    sdk: flutter
