# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: clima_domain
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dartz: 0.10.0
  riverpod: 0.14.0+3
  clima_core:
    path: ../clima_core

dev_dependencies:
  test: 1.17.10
  lint: 1.6.0
