name: clima_core
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.17.3
